# Generated by Django 5.0.2 on 2024-03-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название файла', max_length=200, verbose_name='Название')),
                ('data', models.TextField(help_text='Заполните текстовое наполнение файла', verbose_name='Данные документа')),
            ],
        ),
    ]
